spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/seminar3?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  config:
    activate:
      on-profile: local

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true


  sql:
    init:
      mode: always